
version: '3.9'

services:
  client:
    container_name: client
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - server
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 2052:2052
    environment:
      - NODE_ENV=production
      - PORT=2052
      - HOST=http://yuron.xyz:2052
      - DATABASE_URL=postgresql://admin:admin@db:5432/users?schema=public
      - JWT_SECRET_KEY=JWTBIGsecret
      - TINIFY_TOKEN=6Qvh7qNXNrQ9tzS0mzvwMV1Jbwt1Yn7R
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes: 
  pgdata: {}